# Deploys multiple stages in one AWS account
name: Build and Deploy to Dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v3

      - name: Read project_config.yaml and setup environment
        env:
          ENVIRONMENT: dev
        run: |
          python scripts/main.py >> $GITHUB_ENV

  deploy-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: 
      name: 'dev'
    steps:
      - name: Deploy to Dev
        run: echo "Deploy to Dev"

      - name: Checkout github repository
        uses: actions/checkout@v3

